name: Deploy and Backup Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Send Discord notification - Build Complete
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d \
          '{"content": "👻 gh0stnode.twop0intfive.xyz | Initial build complete. Deploying..."}' \
          $WEBHOOK_URL

      # DEPLOY TO AWS S3
      - name: Deploy to S3 (Public Hosting)
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PUBLIC_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './_site'

      - name: Send Discord notification - S3 Deployed
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d \
          '{"content": "✔️1️ Deployment to primary S3 bucket successful!"}' \
          $WEBHOOK_URL

      # DEPLOY TO AZURE BLOB STORAGE (Commented out)
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy to Azure Blob Storage
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} -d '$web' -s ./_site --overwrite

      # - name: Send Discord notification - Azure Deployed
      #   env:
      #     WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     curl -H "Content-Type: application/json" -d \
      #     '{"content": "✔️2️ Deployment to Azure Blob Storage successful!"}' \
      #     $WEBHOOK_URL

      # DEPLOY TO GOOGLE CLOUD STORAGE (Commented out)
      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1

      # - name: Deploy to Google Cloud Storage
      #   run: |
      #     gsutil -m rsync -d -r ./_site gs://${{ secrets.GCS_BUCKET_NAME }}

      # - name: Send Discord notification - GCS Deployed
      #   env:
      #     WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     curl -H "Content-Type: application/json" -d \
      #     '{"content": "✔️3️ Deployment to Google Cloud Storage successful!"}' \
      #     $WEBHOOK_URL

      # DEPLOY TO CLOUDFLARE PAGES (Placeholder)
      # - name: Deploy to Cloudflare Pages
      #   uses: cloudflare/pages-action@v1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: your-project-name
      #     directory: ./_site
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # - name: Send Discord notification - Cloudflare Pages Deployed
      #   env:
      #     WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     curl -H "Content-Type: application/json" -d \
      #     '{"content": "✔️4️ Deployment to Cloudflare Pages successful!"}' \
      #     $WEBHOOK_URL

      # DEPLOY TO VERCEL (Placeholder)
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     working-directory: ./_site

      # - name: Send Discord notification - Vercel Deployed
      #   env:
      #     WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     curl -H "Content-Type: application/json" -d \
      #     '{"content": "✔️5️ Deployment to Vercel successful!"}' \
      #     $WEBHOOK_URL

      - name: Send Discord notification - All Jobs Complete
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d \
          '{"content": "✅ New blog post deployed to S3 successfully! Azure, GCS, Cloudflare Pages, and Vercel deployments not yet implemented."}' \
          $WEBHOOK_URL