name: Deploy and Backup Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Send Discord notification - Build Complete
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d \
          '{"content": "👻 gh0stnode.twop0intfive.xyz | Initial build complete. Deploying..."}' \
          $WEBHOOK_URL

      # DEPLOY TO GITHUB PAGES
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - name: Send Discord notification - GitHub Pages Deployed
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d \
          '{"content": "✔️ Deployment to GitHub Pages successful!"}' \
          $WEBHOOK_URL

      # DEPLOY TO CLOUDFLARE PAGES (Placeholder)
      # - name: Deploy to Cloudflare Pages
      #   uses: cloudflare/pages-action@v1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: your-project-name
      #     directory: ./_site
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # - name: Send Discord notification - Cloudflare Pages Deployed
      #   env:
      #     WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     curl -H "Content-Type: application/json" -d \
      #     '{"content": "✔️ Deployment to Cloudflare Pages successful!"}' \
      #     $WEBHOOK_URL

      # DEPLOY TO VERCEL (Placeholder)
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     working-directory: ./_site

      # - name: Send Discord notification - Vercel Deployed
      #   env:
      #     WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     curl -H "Content-Type: application/json" -d \
      #     '{"content": "✔️ Deployment to Vercel successful!"}' \
      #     $WEBHOOK_URL

      - name: Send Discord notification - All Jobs Complete
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -d \
          '{"content": "✅ New blog updates deployed to GitHub Pages successfully! Cloudflare Pages and Vercel deployments not yet implemented."}' \
          $WEBHOOK_URL
